CREATE SCHEMA COMMERCE_BANK;

/* 1 Creating CUSTOMER TYPES table*/
CREATE TABLE CUSTOMER_TYPES
(
CUSTOMER_TYPES_ID VARCHAR(15),
CUSTOMER_TYPES_DESC VARCHAR(50),

CONSTRAINT PRIMARY KEY(CUSTOMER_TYPES_ID)
);

/* 2 Creating CUSTOMER table*/
CREATE TABLE CUSTOMER_INFO
(
CUSTOMER_ID INT(10) NOT NULL, 
CUSTOMER_FNAME VARCHAR(20), 
CUSTOMER_LNAME VARCHAR(20),
DOB DATE,
SOCIAL_SECURITY SMALLINT(9),
LOGIN VARCHAR(30),
PASSWORD VARCHAR(30),
ADDRESS VARCHAR(30),
CITY VARCHAR(30),
STATE VARCHAR(20),
ZIP_CODE SMALLINT(6),
CONTACT_INFO BIGINT(10),
EMAIL_ADDRESS VARCHAR (30),
GENDER CHAR(1),

CONSTRAINT PRIMARY KEY(CUSTOMER_ID), FOREIGN KEY (CUSTOMER_TYPES_ID) REFERENCES CUSTOMER_TYPES  
);

/* 3 Creating CUSTOMER PURCH table*/
CREATE TABLE CUSTOMER_PURCH
(
PURCH_ID INT(10),
PURCH_DATE DATE,
CUSTOMER_ID INT(10),
PRODUCT_SERVICE_ID VARCHAR(15),

CONSTRAINT PRIMARY KEY (PURCHASE_ID), FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_INFO, FOREIGN KEY (PRODUCT_SERVICE_ID) REFERENCES PRODUCT_SERVICE
);


/* 4 Creating ACCOUNT TYPES table*/
CREATE TABLE ACCOUNT_TYPES
(
ACCOUNT_TYPES_ID VARCHAR(15),
ACCOUNT_TYPES_DESCRIPTION VARCHAR(40),

CONSTRAINT PRIMARY KEY (ACCOUNT_TYPES_ID)
);

/* 5 Creating ACCOUNTS table*/
CREATE TABLE ACCOUNTS
(
ACCOUNT_ID INT(10),
ACCOUNT_NAME VARCHAR(40),
DATE_OPENED DATE,
ACCOUNT_TYPES_ID INT (15),
CUSTOMER_ID INT (10),

CONSTRAINT PRIMARY KEY(ACCOUNT_ID), FOREIGN KEY(ACCOUNT_TYPES_IED) REFERENCES ACCOUNT_TYPES, FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO
);

/* 6 Creating TRANSACTION TYPES table*/
CREATE TABLE TRANSACTION_TYPES
(
TRANSACTION_TYPES_ID VARCHAR(15),
TRANSACTION_TYPES_DESCRIPTION VARCHAR(40),

CONSTRAINT PRIMARY KEY (TRANSACTION_TYPES_ID)
);

/* 7 Creating TRANSACTION table*/
CREATE TABLE TRANSACTION
(
TRANSACTION_ID INT(10),
PURCH_DATE DATE,
PURCH_ID INT(10),
ACCOUNT_ID INT(10),
TRANSACTION_TYPES_ID VARCHAR(15),

CONSTRAINT PRIMARY KEY(TRANSACTION_ID), FOREIGN KEY(PURCH_ID) REFERENCES CUSTOMER_PURCH, FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS, FOREIGN KEY(TRANSACTION_TYPES_ID) REFERENCES TRANSACTION_TYPES
);

/* 8 Creating MERCH table*/
CREATE TABLE MERCHANTS
(
MERCHANT_ID INT(10),
MERCHANT_NAME VARCHAR(40),
MERCHANTS_PHONE_NO INT(10),
MERCHANTS_CONTACT_EMAIL VARCHAR(40),

CONSTRAINT PRIMARY KEY(MERCHANT_ID)
);

/* 9 Creating PRODUCT & SERVICES table*/
CREATE TABLE PRODUCT_SERVICE
(
PRODUCT_SERVICE_ID VARCHAR(15),
PRODUCT_SERVICE_DESCRIPTION VARCHAR(40),
MERCHANT_ID INT(10),

CONSTRAINT PRIMARY KEY (PRODUCT_SERVICE_ID), FOREIGN KEY(MERCHANT_ID) REFERENCES MERCHANTS
);
